### ISSUE TITLE
in the mac, build image failed with  error returned non-zero exit status 100

### ISSUE THREAD

**Issue by robertchen** [alvistack/vagrant-ubuntu#1]
my env. is mac Ventura 13.0.1
```
$ packer -v
1.8.4

cd vagrant-ubuntu/packer/ubuntu-22.04-virtualbox
$ packer build packer.json
virtualbox-iso: output will be in this color.

==> virtualbox-iso: Retrieving Guest additions
==> virtualbox-iso: Trying /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso
==> virtualbox-iso: Trying /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso
==> virtualbox-iso: /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso => /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso
==> virtualbox-iso: Retrieving ISO
==> virtualbox-iso: Trying ubuntu-22.04.1-live-server-amd64.iso
==> virtualbox-iso: Trying ubuntu-22.04.1-live-server-amd64.iso?checksum=sha256%3A10f19c5b2b8d6db711582e0e27f5116296c34fe4b313ba45f9b201a5007056cb
==> virtualbox-iso: ubuntu-22.04.1-live-server-amd64.iso?checksum=sha256%3A10f19c5b2b8d6db711582e0e27f5116296c34fe4b313ba45f9b201a5007056cb => /Users/robert/.cache/packer/281aa9855752339063385b35198e73db74cd61ba.iso
==> virtualbox-iso: Starting HTTP server on port 8991
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive output-virtualbox-iso/packer-virtualbox-iso-1670424995.vdi with size 131072 MiB...
==> virtualbox-iso: Mounting ISOs...
    virtualbox-iso: Mounting boot ISO...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 3419)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1670424995 --cpu-profile host
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1670424995 --nat-localhostreachable1 on
==> virtualbox-iso: Starting the virtual machine...
    virtualbox-iso: The VM will be run headless, without a GUI. If you want to
    virtualbox-iso: view the screen of the VM, connect via VRDP without a password to
    virtualbox-iso: rdp://0.0.0.0:5935
==> virtualbox-iso: Waiting 1s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Using SSH communicator to connect: 127.0.0.1
==> virtualbox-iso: Waiting for SSH to become available...
==> virtualbox-iso: Timeout waiting for SSH.
==> virtualbox-iso: Cleaning up floppy disk...
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored after 2 hours 1 minute: Timeout waiting for SSH.

==> Wait completed after 2 hours 1 minute

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Timeout waiting for SSH.
```

In the console, I saw the error returned non-zero exit status 100
![VirtualBox_packer-virtualbox-iso-1670424321_07_12_2022_09_50_20](https://user-images.githubusercontent.com/1059160/206215488-d16e9fc3-23a3-4c72-894c-849bdd43294e.png)

**Comment by robertchen** [comment]
please help? thx

**Comment by hswong3i** [comment]
It looks like failed when running apt-get update. Are you building without internet access?

On the other hand, you should able to use my pre-build vagrant box for VirtualBox on Mac. Are you going to customize the packer build procedures?

**Comment by robertchen** [comment]
Thanks for reply, my MAC is always connected to internet.  virtualbox network is NAT. 

<img width="767" alt="image" src="https://user-images.githubusercontent.com/1059160/206313030-9399af2f-9b43-4346-8b30-b73a1c259e8d.png">

**Comment by robertchen** [comment]
I changed eth0 to enp0s3 in the user-data file, now it works for updating and downloading. 
Seems virtualbox in mac uses enp0s3 for ubuntu 22.04.
But now I got another error:
` virtualbox-iso: ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/api': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
`

**Comment by hswong3i** [comment]
> I changed eth0 to enp0s3 in the user-data file, now it works for updating and downloading. Seems virtualbox in mac uses enp0s3 for ubuntu 22.04. 

Umm.... Due to https://github.com/alvistack/vagrant-ubuntu/blob/master/packer/ubuntu-22.04-virtualbox/packer.json#L19, I had hard coded with legacy network interface name by `net.ifnames=0`. It shouldn't fallback as those newly non-predictable network interface name.

> But now I got another error: `virtualbox-iso: ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/api': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>`

This usually due to unstable from `https://galaxy.ansible.com/api/api` server side, I also face a lots of fail in my CI build due to that. A retry should simply help this.

**Comment by robertchen** [comment]
thx, close this one, will open another one for ansible
