### ISSUE TITLE
ansible failed to handshake while building ubuntu 22.04 virtualbox 

### ISSUE THREAD

**Issue by robertchen** [alvistack/vagrant-ubuntu#2]
my env. is mac Ventura 13.0.1

$ packer -v
1.8.4

==> virtualbox-iso: Provisioning with Ansible...
    virtualbox-iso: Setting up proxy adapter for Ansible....
    virtualbox-iso: Executing Ansible Galaxy
    virtualbox-iso: Starting galaxy collection install process
    virtualbox-iso: Process install dependency map
    virtualbox-iso: Starting collection install process
    virtualbox-iso: Downloading https://galaxy.ansible.com/download/ansible-posix-1.4.0.tar.gz to /Users/robert/.ansible/tmp/ansible-local-74041ktj2ise3/tmpuofdeu13/ansible-posix-1.4.0-b_nlocjn
    virtualbox-iso: Installing 'ansible.posix:1.4.0' to '/Users/robert/.ansible/collections/ansible_collections/ansible/posix'
    virtualbox-iso: ansible.posix:1.4.0 was installed successfully
    virtualbox-iso: Downloading https://galaxy.ansible.com/download/community-docker-3.3.1.tar.gz to /Users/robert/.ansible/tmp/ansible-local-74041ktj2ise3/tmpuofdeu13/community-docker-3.3.1-opxt6w1b
    virtualbox-iso: Installing 'community.docker:3.3.1' to '/Users/robert/.ansible/collections/ansible_collections/community/docker'
    virtualbox-iso: community.docker:3.3.1 was installed successfully
    virtualbox-iso: Downloading https://galaxy.ansible.com/download/containers-podman-1.10.1.tar.gz to /Users/robert/.ansible/tmp/ansible-local-74041ktj2ise3/tmpuofdeu13/containers-podman-1.10.1-2vdt42kw
    virtualbox-iso: Installing 'containers.podman:1.10.1' to '/Users/robert/.ansible/collections/ansible_collections/containers/podman'
    virtualbox-iso: containers.podman:1.10.1 was installed successfully
==> virtualbox-iso: Executing Ansible: ansible-playbook -e packer_build_name="virtualbox-iso" -e packer_builder_type=virtualbox-iso -e packer_http_addr=10.0.2.2:8815 --ssh-extra-args '-o IdentitiesOnly=yes' -e ansible_ssh_private_key_file=/var/folders/jv/bf9rbm597_97zs41mhhj9sx00000gn/T/ansible-key1454949687 -i ./packer-provisioner-ansible3158424114 /Users/robert/src/robert-packer/*****-ubuntu/packer/ubuntu-22.04-virtualbox/packer.yml
    virtualbox-iso:
    virtualbox-iso: PLAY [prepare | all] ***********************************************************
    virtualbox-iso:
    virtualbox-iso: TASK [redhat | subscription-manager register] **********************************
**==> virtualbox-iso: failed to handshake**
    **virtualbox-iso: fatal: [default]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Unable to negotiate with 127.0.0.1 port 56137: no matching host key type found. Their offer: ssh-rsa", "unreachable": true}**
    virtualbox-iso:
    virtualbox-iso: PLAY RECAP *********************************************************************
    virtualbox-iso: default                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
    virtualbox-iso:
==> virtualbox-iso: Provisioning step had errors: Running the cleanup provisioner, if present...
==> virtualbox-iso: Cleaning up floppy disk...
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored after 12 minutes 11 seconds: Error executing Ansible: Non-zero exit status: exit status 4

**Comment by hswong3i** [comment]
It should be allowed by https://github.com/alvistack/vagrant-ubuntu/blob/master/packer/ubuntu-22.04-virtualbox/user-data#L90-L97:
```
            mkdir -p /etc/ssh/sshd_config.d; \
            echo "PubkeyAcceptedKeyTypes +ssh-rsa" > /etc/ssh/sshd_config.d/10-PubkeyAcceptedKeyTypes-ssh-rsa.conf; \
            chmod 600 /etc/ssh/sshd_config.d/10-PubkeyAcceptedKeyTypes-ssh-rsa.conf; \
            mkdir -p /etc/ssh/ssh_config.d; \
            echo "Host *" >> /etc/ssh/ssh_config.d/10-PubkeyAcceptedKeyTypes-ssh-rsa.conf; \
            echo "    HostkeyAlgorithms +ssh-rsa" >> /etc/ssh/ssh_config.d/10-PubkeyAcceptedKeyTypes-ssh-rsa.conf; \
            echo "    PubkeyAcceptedKeyTypes +ssh-rsa" >> /etc/ssh/ssh_config.d/10-PubkeyAcceptedKeyTypes-ssh-rsa.conf; \
            chmod 644 /etc/ssh/ssh_config.d/10-PubkeyAcceptedKeyTypes-ssh-rsa.conf; \
```

**Comment by robertchen** [comment]
thx, resolved

**Comment by hswong3i** [comment]
Gentlemen, are you customizing the packer build procedure for your own needs? 

If you reuse code from this repo directly and failed, it is welcome for a bug report and I will surely solve it for you. But at least, try once without modify the code.

If you are using my code as reference for learning packer build process, packer official repo issue tracker could be more useful than here, at least I don't have Mac nor Windows on hand for debugging together with you ;-(

**Comment by robertchen** [comment]
I did not change any code, just try to run it on mac, seems different. Thank you for great work, will try as much as I can. thx
